Модуляция
htmlacademy-javascript/1538503-kekstagram-simple-27 pull request #4
Opened 2022-10-26 16:00 UTC by wyoming228

2022-10-26 16:56 UTC, ArtMan-8 requested changes

2022-10-26 16:56 UTC, ArtMan-8 commented on js/data.js
> +newArray();
зачем вызов?

2022-10-26 16:56 UTC, ArtMan-8 commented on js/data.js
> +const newArray = () => Array.from({length: 25}, getPicDescribtion);
Это функция, а не значение. Значит get..., или generate... а что мы создаём?

2022-10-26 16:56 UTC, ArtMan-8 commented on js/data.js
> +export {getPicDescribtion};
Пишем экспорты через запятую.
```suggestion
export { newArray, getPicDescribtion };
```

2022-10-26 16:56 UTC, ArtMan-8 commented on js/util.js
> +getRandomIntInclusive(1,10);
зачем?

2022-10-26 16:56 UTC, ArtMan-8 commented on js/util.js
> +const lineLenght = (line, maxLenght) => line.length < maxLenght;
Это функция-предикат, возвращает булево значение, а не просто значение. Предикаты обычно начинаются с is..., реже has...

2022-10-26 16:56 UTC, ArtMan-8 commented on js/util.js
> +lineLenght('', 130 );
зачем?

2022-10-26 16:56 UTC, ArtMan-8 commented on js/util.js
> +export {getRandomIntInclusive};
```suggestion
export { getRandomIntInclusive, getRandomArrayElement };
```

2022-10-26 16:56 UTC, ArtMan-8 commented on js/util.js
> +function getRandomIntInclusive (min, max) {
Ещё раз обращаю внимание - где-то стрелочные функции у тебя, где-то декларативные. Нужны в одном стиле

2022-10-26 18:19 UTC, wyoming228 commented on js/data.js
> +newArray();
вызывал потому что линтер ругался: assigned but never used

2022-10-26 18:19 UTC, wyoming228 commented on js/util.js
> +getRandomIntInclusive(1,10);
аналогично, чтоб линтер не ругался

2022-10-26 18:20 UTC, wyoming228 commented on js/util.js
> +lineLenght('', 130 );
тут тоже линтер

2022-10-26 18:22 UTC, ArtMan-8 commented on js/data.js
> +newArray();
Если её экспортируешь, линтер уже не должен ругаться.

2022-10-26 18:22 UTC, ArtMan-8 commented on js/util.js
> +getRandomIntInclusive(1,10);
Если её экспортируешь, линтер уже не должен ругаться.

2022-10-26 18:22 UTC, ArtMan-8 commented on js/util.js
> +lineLenght('', 130 );
Если её экспортируешь, линтер уже не должен ругаться. ТОже )

2022-10-26 18:23 UTC, wyoming228 commented on js/data.js
> +const newArray = () => Array.from({length: 25}, getPicDescribtion);
создаем массив случайных фото. получается лучше именовать как-нибудь типа genPicArray ?

2022-10-26 18:34 UTC, wyoming228 commented on js/util.js
> +function getRandomIntInclusive (min, max) {
у меня были сложности с синтаксисом стрелочных функций, поэтому присутствовал разнобой

2022-10-26 18:47 UTC, ArtMan-8 commented on js/data.js
> +const newArray = () => Array.from({length: 25}, getPicDescribtion);
Да, только не сокращай названия - `generateRandomPhotos`, как пример. Множественное число уже говорит, что это массив. Постфиксы `array`, и подобные не нужны.

2022-10-27 15:54 UTC, ArtMan-8 approved these changes

2022-10-27 15:54 UTC, merged