Правда или действие
htmlacademy-javascript/1538503-kekstagram-simple-27 pull request #6
Opened 2022-11-17 06:01 UTC by wyoming228

2022-11-17 07:42 UTC, ArtMan-8 requested changes

2022-11-17 07:42 UTC, ArtMan-8 commented on js/util.js
> +const minCommentLength = 20;
Константы задаются полностью большими буквами `MIN_COMMENTH_LENGTH`

2022-11-17 07:42 UTC, ArtMan-8 commented on pristine/pristine.js
> +(function (global, factory) {
почему не минифицированный, и не в папке vendor?
Сторонние скрипты обычно складывают в папку vendor или lib.

2022-11-17 07:42 UTC, ArtMan-8 commented on js/user-form.js
> +pristine.addValidator(userForm.querySelector('.textdescription'), isAllowableLenght, 'От 20 до 140 символов');
Навешиваем явно. Сейчас падает ошибка, что pristine undefined. Это действие происходит раньше, чем загрузился скрипт.

2022-11-17 07:42 UTC, ArtMan-8 commented on js/user-form.js
> +  fileSelect.addEventListener('change', () => {
если просто нужно вызвать функцию, можно так передать,
```suggestion
  fileSelect.addEventListener('change', openModal)
```

2022-11-17 20:23 UTC, wyoming228 commented on pristine/pristine.js
> +(function (global, factory) {
не знал как подключать. в демке увидел, что пристин в корне была

2022-11-17 20:23 UTC, wyoming228 commented on js/user-form.js
> +pristine.addValidator(userForm.querySelector('.textdescription'), isAllowableLenght, 'От 20 до 140 символов');
а как это отследить? не совсем понимаю как это решить

2022-11-22 06:23 UTC, ArtMan-8 commented on js/user-form.js
> +pristine.addValidator(userForm.querySelector('.textdescription'), isAllowableLenght, 'От 20 до 140 символов');
Например это всё обернуть в функцию, которая и будет добавлять этот обработчик. Саму функцию так же можно вызвать в main, после всей отрисовки.

Типа
```
const addFormValidate = () => {
   pristine.addValidator()
}
```

2022-11-22 10:33 UTC, ArtMan-8 approved these changes

2022-11-22 10:33 UTC, merged